# Generated by Django 3.2.8 on 2021-10-31 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinnerdash', '0002_recipe_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='likes',
            new_name='image',
        ),
    ]
