# Generated by Django 3.2.8 on 2021-10-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinnerdash', '0003_rename_likes_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(default='Heat Up'),
            preserve_default=False,
        ),
    ]
