# Generated by Django 3.2.8 on 2021-10-28 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
    ]
